name: life_app
description: "Offline-first wellness companion built with Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_analytics: ^11.1.0
  firebase_crashlytics: ^4.0.2
  cloud_functions: ^5.0.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  flutter_local_notifications: ^17.2.1
  flutter_riverpod: ^2.5.1
  purchases_flutter: ^7.1.0
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.2
  file_picker: ^8.0.6
  share_plus: ^9.0.0
  path: ^1.9.0
  just_audio: ^0.9.36
  audio_session: ^0.1.19
  shared_preferences: ^2.2.3
  characters: ^1.3.0
  timezone: ^0.9.4
  flutter_native_timezone: ^2.0.0
  flutter_foreground_task: ^3.10.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  workmanager: ^0.5.2
  record: ^5.0.5
  health: ^6.1.1
  equatable: ^2.0.5
  uuid: ^4.4.0
  flutter_tts: ^4.0.2
  pdf: ^3.11.0
  dynamic_color: ^1.8.0
  home_widget: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_test: ^2.2.0
  build_runner: ^2.4.11
  isar_generator:
    path: packages/isar_generator
  flutter_lints: ^4.0.0
  http: ^1.2.1
  path_provider_platform_interface: ^2.1.2
  fake_cloud_firestore: ^3.0.0
  firebase_auth_mocks: ^0.13.0
  riverpod: ^2.5.1
  very_good_analysis: ^6.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - lib/l10n/
    - assets/audio/manifest.json
    - assets/audio/app/
    - assets/maps/

dependency_overrides:
  analyzer: ^6.4.1
  _fe_analyzer_shared: ^67.0.0
  dart_style: ^2.3.6
  flutter_native_timezone:
    path: packages/flutter_native_timezone
