name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @Collection.
version: 3.1.0+1
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^8.2.0
  build: ^4.0.0
  dart_style: ^3.1.2
  dartx: ^1.1.0
  glob: ^2.0.2
  isar: 3.1.0+1
  path: ^1.8.1
  source_gen: ^4.0.1
  xxh3: ^1.0.1

dev_dependencies:
  build_test: ^3.4.1
  matcher: ^0.12.12
  test: ^1.21.0
  very_good_analysis: ^3.0.1
